### ISSUE TITLE
Research montetization providers

### ISSUE THREAD

**Issue by reediculous456** [reediculous456/MusicLink#12]
### RESEARCH
---------------------------------------------
#### Detailed Description
Search around for different AD providers for the android platform.
Things to look for:
* Do they provide us ADs or do we have to provide our own?
* If they provide ADs, can we choose what ADs are shown?
* What is the rate? (e.x. you get 1¢/ad)
* What types of ADs are available? (pop up, banner, etc)
* What type of AD best fits our user experience?

**Comment by katievo-1** [comment]
### Ad Providers: Listed in order of preference 

1. Google Ads (AdMob)
- provides us with ads
- we can block certain ads from being shown. Generally, will show highest performing ads
- it's free to use!
- around $6/1000 RPM (rate per impressions)
- Provides banner ads, full page ads or customization for formatting for ads
- Allows for text, image or video ads that are interact-able
2. Media.net
- provides us with ads
- no, they choose ads based on "relative key words" associated with our application
- free to sign up, premium features cost extra
- around $5/1000 RPM
- Provides banner, interstitial and rewarded video ad options 
3. InMobi
- provides ads
- has an "opt out" option to filter ads shown
- unknown until after signing up and verifying application
- around $2/1000 CPM (click per impressions)
- provides video and native ads

_For our application, a banner ad would work best for the UI we have in mind. It will take up little space and can be easily added at the bottom of each page on our app. We can have images and texts with the option to opt-out of in-app ads in the banner._
